name: 'Action to notify issues'
description: 'notify issue comments'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  url:
    description: |
      发送通知的 web hook url
    required: true
    default: ''
  issue_title:
    description: |
      issue title
    required: true
    default: ''
  issue_body:
    description: |
      issue body
    required: true
    default: ''
  issue_link_url:
    description: |
      issue link url
    required: true
    default: ''
